### ISSUE TITLE
ongoing dplyr deprecation warning

### ISSUE THREAD

**Issue by AdamCSmithCWS** [bbsBayes/bbsBayes2#24]
following on the recent merging of PR #18 , `generate_indices()` is till producing a dplyr warning.

@steffilazerte, any ideas what we've missed?

`inds <- generate_indices(fit, regions = "stratum")`
Processing region stratum
Warning message:
Returning more (or less) than 1 row per `summarise()` group was deprecated in dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()` always returns an ungrouped data frame and adjust accordingly.
ℹ The deprecated feature was likely used in the tidyr package.
  Please report the issue at <https://github.com/tidyverse/tidyr/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

**Comment by steffilazerte** [comment]
Could you point out where this is happening? All the test failures I'm seeing are related to a change in a snapshot?

**Comment by AdamCSmithCWS** [comment]
I haven't figured out where it's happening. I don't see any tests failing as a result of the warning. i only see the warning when running the function. 

I haven't fixed the snapshot failures because I suck, and I haven't figured out how, yet. But I'm making progress.

**Comment by steffilazerte** [comment]
Hmm, what is the code you're running? Perhaps I don't have a test for that!

No worries about the snapshot failures, they're tricky! Happy to walk through that with you at some point if that would be helpful!

**Comment by AdamCSmithCWS** [comment]
it's just any call to generate_indices() with the defaults and (I think) for any of the models. but it's a bit tricky to recreate because the dplyr warning only gets displayed every8 hours.

**Comment by steffilazerte** [comment]
Are you sure you've pulled the changes and then rebuilt the package locally? (Silly question, I know, but this gets me all the time)

**Comment by steffilazerte** [comment]
Also, try options(lifecycle_verbosity = "error") to make the error happen everytime (or restart R)

**Comment by AdamCSmithCWS** [comment]
Oh dear. Embarrassing! I had updated `dplyr` but not `tidyr`, and that was (I'm pretty sure) causing the problem.

**Comment by AdamCSmithCWS** [comment]
Thanks @steffilazerte....
...now let's see....what else can I break... 🥇

**Comment by steffilazerte** [comment]
Break it all! Let's see how robust it is ;)
