### ISSUE TITLE
Specifying Output Directory for the Model and Stan Sampling Chains?

### ISSUE THREAD

**Issue by hengxingzou** [bbsBayes/bbsBayes2#51]
First of all, thank you for all the authors and contributors--I find this package extremely useful.

When I run the model of a particular species, I notice that all Stan outputs are automatically generated as `.csv` files in my working directory (e.g., `BBS_STAN_first_diff_nonhier_2023-08-01-3.csv` for chain 3). When running models for multiple species in a row, the .csv files seem to have interfered each other because their names are identical and only depend on the model type, not the species.

When I try to export the model to a different directory to avoid the problem, I notice that the Stan outputs are still automatically generated in my working directory, and I am now unable to save the model to my specified directory because compiling the `.rds` file seems to require the Stan output, which the function is now unable to access because they are not under the same directory.

When I try to run two different models in two R sessions, one of them still failed even all sampling are complete. The error seems to have occurred at the step of exporting the fitted model, with the message `Error: All variables in all chains must have the same length.`

I have noticed that in the [example code of replicating CWS analyses](https://github.com/AdamCSmithCWS/CWS_BBS_2021_Analyses/blob/main/1_CWS_BBS_Fit_gamye_models_species_loop.R), which if I understand correctly is a prototype of the workflow in `bbsBayes2`, there are commands specifying the directory of Stan outputs (line 129 of the linked file), and the script is apparently able to handle multiple species in a row, but I am not sure whether the same options and functionalities are built into `bbsBayes2`.

It would be great if you have any insights. Thanks again for this amazing package!

**Comment by AdamCSmithCWS** [comment]
Thanks for this. You're right, the default model-date naming creates conflicts. 

We'll be generating a new release soon (the 2023 release just dropped on the USGS servers). I'll try to make sure we figure out a way to avoid these file-naming issues with the defaults. 

Short-term fix, you can specify an output directory and a file name for each model run using the `output_dir` and/or the `output_basename` arguments in the `run_model()` function.  I've used that option in this new advanced example showing a [covariate elaboration of a base model](https://bbsbayes.github.io/bbsBayes2/articles/advanced.html#example---modifying-a-model-to-include-a-covariate).

e.g.,

`run_model(..., output_basename = "my_species", output_dir = "my_directory")`

**Comment by hengxingzou** [comment]
That works--thank you! Looking forward to the new release.
