### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by steffilazerte** [bbsBayes/bbsBayes2#86]
Hi @AdamCSmithCWS! 

I've been struggling with figures produced by precompilation of vignettes in another project and came to look at the ones here to remind myself of how it's done.

I think I've figured out my problem, but it made me realize a couple of things.

One thing I realized is that figures *with* alt text (but no caption) are rendered with html notation (see [before](https://github.com/bbsBayes/bbsBayes2/blob/1b1a8f83cd086fc92c35fa09fdcda97e159dd6ca/vignettes/articles/bbsBayes2.Rmd.orig#L604-L609) and [after](https://github.com/bbsBayes/bbsBayes2/blob/1b1a8f83cd086fc92c35fa09fdcda97e159dd6ca/vignettes/articles/bbsBayes2.Rmd#L752)), and those *without* alt text get rendered into the precompiled Rmd file using Markdown notation (see [before](https://github.com/bbsBayes/bbsBayes2/blob/1b1a8f83cd086fc92c35fa09fdcda97e159dd6ca/vignettes/articles/bbsBayes2.Rmd.orig#L415-L417) and [after](https://github.com/bbsBayes/bbsBayes2/blob/1b1a8f83cd086fc92c35fa09fdcda97e159dd6ca/vignettes/articles/bbsBayes2.Rmd#L486C58-L486C80)). 

This is important, because the figure path in the non-alt text example isn't correctly fixed in your precompile script (see that the [first](https://bbsbayes.github.io/bbsBayes2/articles/bbsBayes2.html#additional-steps-for-spatial-models) example works, but you're actually missing the figure in the [second](https://bbsbayes.github.io/bbsBayes2/articles/bbsBayes2.html#spaghetti-plots-to-show-uncertainty-in-population-trajectories) example).

At any rate, I was able to figure out my problems because you had examples of both here. And so I thought it was only fair that I let you know that one of your figures isn't rendering properly 😁 .

**Comment by AdamCSmithCWS** [comment]
Thank you @steffilazerte.  🥇 
I had been struggling to understand why I was getting these inconsistent renderings. 

Many thanks.

**Comment by AdamCSmithCWS** [comment]
Fixed
